// Package decoder implements the Qi UTXO event decoder (M2).
// Events commit atomically with the spine block row via the injected pgx.Tx.
package decoder

import (
	"context"
	"encoding/hex"
	"fmt"
	"log/slog"
	"math/big"
	"strings"

	"github.com/jackc/pgx/v5"

	"github.com/leviquai/qi-index/internal/chain"
	"github.com/leviquai/qi-index/internal/qidecode"
	"github.com/leviquai/qi-index/internal/rpcclient"
)

type Decoder struct {
	log *slog.Logger
}

// New returns a Decoder; log may be nil.
func New(log *slog.Logger) *Decoder {
	if log == nil {
		log = slog.Default()
	}
	return &Decoder{log: log}
}

func (d *Decoder) DecodeApply(ctx context.Context, tx pgx.Tx, blocks []chain.Block) error {
	for _, b := range blocks {
		if err := d.applyBlock(ctx, tx, b); err != nil {
			return fmt.Errorf("block %d (%s): %w", b.Height, b.Hash[:min(10, len(b.Hash))], err)
		}
	}
	return nil
}

// DecodeRollback reverts UTXO events; blocks must be tip→ancestor order.
func (d *Decoder) DecodeRollback(ctx context.Context, tx pgx.Tx, blocks []chain.Block) error {
	for _, b := range blocks {
		if err := d.rollbackBlock(ctx, tx, b); err != nil {
			return fmt.Errorf("rollback block %d (%s): %w", b.Height, b.Hash[:min(10, len(b.Hash))], err)
		}
	}
	return nil
}

func (d *Decoder) applyBlock(ctx context.Context, tx pgx.Tx, b chain.Block) error {
	body, err := rpcclient.ParseBody(b.Raw)
	if err != nil {
		return fmt.Errorf("parse body: %w", err)
	}

	var creates, spends, convOuts, etxCreates int

	for _, raw := range body.Transactions {
		if uint64(raw.Type) != uint64(qidecode.TxTypeQi) {
			continue
		}
		txHash, err := decodeHash(raw.Hash)
		if err != nil {
			return fmt.Errorf("qi tx hash %q: %w", raw.Hash, err)
		}

		for _, in := range raw.Inputs {
			prevHash, err := decodeHash(in.PreviousOutPoint.TxHash)
			if err != nil {
				return fmt.Errorf("input outpoint hash: %w", err)
			}
			pubkey, err := decodeHex(in.PubKey)
			if err != nil {
				return fmt.Errorf("input pubkey: %w", err)
			}
			tag, err := tx.Exec(ctx, `
				UPDATE utxos
				SET spent_block = $1, spent_tx = $2, spender_pubkey = $3
				WHERE tx_hash = $4 AND tx_index = $5
				  AND spent_block IS NULL AND trimmed_block IS NULL`,
				b.Height, txHash, pubkey,
				prevHash, int32(in.PreviousOutPoint.Index),
			)
			if err != nil {
				return fmt.Errorf("mark spent: %w", err)
			}
			if tag.RowsAffected() == 0 {
				d.log.Warn("spend matched no unspent utxo", "tx", txHash, "index", in.PreviousOutPoint.Index, "block", b.Height)
			}
			spends++
		}

		for idx, out := range raw.Outputs {
			addrBytes, err := decodeAddr(out.Address)
			if err != nil {
				return fmt.Errorf("output address %q: %w", out.Address, err)
			}

			if !isQiScopeBytes(addrBytes) {
				if _, err := tx.Exec(ctx, `
					INSERT INTO conversion_outputs (tx_hash, output_index, to_address, denomination, block_height)
					VALUES ($1, $2, $3, $4, $5)
					ON CONFLICT DO NOTHING`,
					txHash, int32(idx), addrBytes, uint8(out.Denomination), b.Height,
				); err != nil {
					return fmt.Errorf("conversion output insert: %w", err)
				}
				convOuts++
				continue
			}

			lockHeight := uint64(0)
			if out.Lock != nil && out.Lock.V != nil {
				lockHeight = out.Lock.V.Uint64()
			}
			trimDeadline := qidecode.TrimDeadline(uint8(out.Denomination), b.Height)

			if _, err := tx.Exec(ctx, `
				INSERT INTO utxos (
					tx_hash, tx_index, address, denomination, lock_height, source,
					created_block, created_tx, trim_deadline
				) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
				ON CONFLICT (tx_hash, tx_index) DO NOTHING`,
				txHash, int32(idx), addrBytes,
				uint8(out.Denomination), lockHeight, qidecode.SourceQiTx,
				b.Height, txHash,
				nullIfZero(trimDeadline),
			); err != nil {
				return fmt.Errorf("utxo insert: %w", err)
			}
			creates++
		}
	}

	// body.OutboundETXs are generated by this block and applied downstream — do not create UTXOs from them.
	for _, raw := range body.Transactions {
		if uint64(raw.Type) != uint64(qidecode.TxTypeExternal) || raw.EtxType == nil || raw.To == nil {
			continue
		}
		toBytes, err := decodeAddr(*raw.To)
		if err != nil {
			return fmt.Errorf("etx to address %q: %w", *raw.To, err)
		}
		if !isQiScopeBytes(toBytes) {
			continue
		}

		etxHash, err := decodeHash(raw.Hash)
		if err != nil {
			return fmt.Errorf("etx hash %q: %w", raw.Hash, err)
		}

		switch uint64(*raw.EtxType) {
		case uint64(qidecode.ETXTypeCoinbase):
			if err := d.insertCoinbaseETXOutputs(ctx, tx, etxHash, toBytes, raw, b.Height); err != nil {
				return err
			}
			etxCreates++

		case uint64(qidecode.ETXTypeConversion):
			if raw.Value == nil || raw.Value.V == nil {
				continue
			}
			gasLimit := uint64(0)
			if raw.Gas != nil {
				gasLimit = uint64(*raw.Gas)
			}
			if err := d.insertConversionETXOutputs(ctx, tx, etxHash, toBytes, raw.Value.V, gasLimit, b.Height); err != nil {
				return err
			}
			etxCreates++
		}
	}

	trimmed, err := sweepTrims(ctx, tx, b.Height)
	if err != nil {
		return fmt.Errorf("trim sweep: %w", err)
	}

	d.log.Debug("block decoded",
		"height", b.Height,
		"creates", creates, "spends", spends,
		"conv_outputs", convOuts, "etx_creates", etxCreates,
		"trimmed", trimmed,
	)
	return nil
}

func (d *Decoder) insertCoinbaseETXOutputs(
	ctx context.Context, tx pgx.Tx,
	etxHash []byte, toBytes []byte,
	raw rpcclient.RawTx, blockHeight uint64,
) error {
	if raw.Input == nil || len(*raw.Input) == 0 {
		d.log.Warn("coinbase ETX has no input data; skipping", "hash", raw.Hash)
		return nil
	}
	lockupByte := (*raw.Input)[0]
	if int(lockupByte) >= 4 { // params.LockupByteToBlockDepth has indices 0–3
		d.log.Warn("coinbase ETX lockup byte out of range", "hash", raw.Hash, "byte", lockupByte)
		return nil
	}
	if raw.Value == nil || raw.Value.V == nil {
		return nil
	}

	outputs := qidecode.CoinbaseETXOutputs(raw.Value.V, lockupByte, blockHeight)
	idx := int32(0)
	for _, o := range outputs {
		for j := uint64(0); j < o.Count; j++ {
			trimDeadline := qidecode.TrimDeadline(o.Denomination, blockHeight)
			if _, err := tx.Exec(ctx, `
				INSERT INTO utxos (
					tx_hash, tx_index, address, denomination, lock_height, source,
					created_block, created_tx, trim_deadline
				) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
				ON CONFLICT (tx_hash, tx_index) DO NOTHING`,
				etxHash, idx, toBytes,
				o.Denomination, o.LockHeight, qidecode.SourceCoinbaseETX,
				blockHeight, etxHash,
				nullIfZero(trimDeadline),
			); err != nil {
				return fmt.Errorf("coinbase utxo insert idx %d: %w", idx, err)
			}
			idx++
		}
	}
	return nil
}

func (d *Decoder) insertConversionETXOutputs(
	ctx context.Context, tx pgx.Tx,
	etxHash []byte, toBytes []byte,
	value *big.Int, gasLimit, blockHeight uint64,
) error {
	outputs := qidecode.ConversionETXOutputs(value, blockHeight, gasLimit)
	idx := int32(0)
	for _, o := range outputs {
		for j := uint64(0); j < o.Count; j++ {
			trimDeadline := qidecode.TrimDeadline(o.Denomination, blockHeight)
			if _, err := tx.Exec(ctx, `
				INSERT INTO utxos (
					tx_hash, tx_index, address, denomination, lock_height, source,
					created_block, created_tx, trim_deadline
				) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
				ON CONFLICT (tx_hash, tx_index) DO NOTHING`,
				etxHash, idx, toBytes,
				o.Denomination, o.LockHeight, qidecode.SourceConversionETX,
				blockHeight, etxHash,
				nullIfZero(trimDeadline),
			); err != nil {
				return fmt.Errorf("conversion utxo insert idx %d: %w", idx, err)
			}
			idx++
		}
	}
	return nil
}

// sweepTrims trims eligible UTXOs at blockHeight. lock_height=0 guard implements
// the PR #2736 invariant: locked UTXOs are exempt from consensus trimming.
func sweepTrims(ctx context.Context, tx pgx.Tx, blockHeight uint64) (int64, error) {
	tag, err := tx.Exec(ctx, `
		UPDATE utxos
		SET trimmed_block = $1
		WHERE trim_deadline = $1
		  AND spent_block   IS NULL
		  AND trimmed_block IS NULL
		  AND lock_height   = 0`,
		blockHeight,
	)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

func (d *Decoder) rollbackBlock(ctx context.Context, tx pgx.Tx, b chain.Block) error {
	if _, err := tx.Exec(ctx,
		`UPDATE utxos SET trimmed_block = NULL WHERE trimmed_block = $1`,
		b.Height,
	); err != nil {
		return fmt.Errorf("un-trim: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		UPDATE utxos
		SET spent_block = NULL, spent_tx = NULL, spender_pubkey = NULL
		WHERE spent_block = $1`,
		b.Height,
	); err != nil {
		return fmt.Errorf("un-spend: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`DELETE FROM utxos WHERE created_block = $1`,
		b.Height,
	); err != nil {
		return fmt.Errorf("delete created utxos: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`DELETE FROM conversion_outputs WHERE block_height = $1`,
		b.Height,
	); err != nil {
		return fmt.Errorf("delete conversion outputs: %w", err)
	}
	return nil
}

// isQiScopeBytes mirrors common.Address.IsInQiLedgerScope: byte[1] >= 0x80.
func isQiScopeBytes(addr []byte) bool {
	return len(addr) == 20 && addr[1] >= 0x80
}

func decodeHash(h string) ([]byte, error) {
	h = strings.TrimPrefix(h, "0x")
	b, err := hex.DecodeString(h)
	if err != nil {
		return nil, err
	}
	if len(b) != 32 {
		return nil, fmt.Errorf("expected 32 bytes, got %d", len(b))
	}
	return b, nil
}

func decodeAddr(h string) ([]byte, error) {
	h = strings.TrimPrefix(h, "0x")
	b, err := hex.DecodeString(h)
	if err != nil {
		return nil, err
	}
	if len(b) != 20 {
		return nil, fmt.Errorf("expected 20 bytes, got %d", len(b))
	}
	return b, nil
}

func decodeHex(h string) ([]byte, error) {
	h = strings.TrimPrefix(h, "0x")
	if h == "" {
		return nil, nil
	}
	return hex.DecodeString(h)
}

func nullIfZero(v uint64) any {
	if v == 0 {
		return nil
	}
	return v
}
